# Используем базовый образ Python
FROM python:3.9-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы программы в контейнер
COPY RockPaperScissorsGame.py .

# Указываем команду для запуска программы
CMD ["python", "RockPaperScissorsGame.py"]
